version: '3.7'

services:

  db-pass-in:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passin
    networks:
      - passin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgresql://admin:admin@db-pass-in:5432/passin
      - API_BASE_URL=http://localhost:3333
      - PORT=3333
    depends_on:
      - db-pass-in
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  postgres-data: {}